### ISSUE TITLE
Instructors хуудсыг хийж дуусгах

### ISSUE THREAD

**Issue by javkhlantS** [EnroseTeam/LMS#62]
Figma design файлын Other Pages доторх 47_instructors_list_v1 загварыг ашиглаж хийх. Pagination-г хийхгүй орхих. Filter хэсгийг button маягаар хийгээд үлдээх.

**Comment by binderiyats** [comment]
Search болон Pagination хэсгүүд ажилгаагүй. DropDown бүрэн бус ажилгаатай байна.
